name: Check code style

on:
  push

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
            pip3 install -r requirements.txt
            pip3 install pydocstyle flake8
        name: Install Python requirements
      - run: |
            python3 -m flake8 .
        name: Run flake8 checks
      - run: |
            python3 -m pydocstyle .
        name: Run pydocstyle checks
